"""
Signal 1: LLM-based classifier via Groq.

Returns a float in [0.0, 1.0] where 0.0 = very likely human, 1.0 = very likely AI.
"""

import os
import re
from groq import Groq

_client: Groq | None = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY environment variable is not set")
        _client = Groq(api_key=api_key)
    return _client


_SYSTEM_PROMPT = """You are an expert AI-content detector. Your only job is to estimate the
probability that a piece of text was generated by an AI language model rather than written by a human.

Respond with a single JSON object and nothing else:
{"score": <float between 0.0 and 1.0>}

Where 0.0 means you are certain the text is human-written and 1.0 means you are certain it is AI-generated.
Consider: semantic coherence, writing style uniformity, sentence structure variety, tone consistency,
overly balanced phrasing, and absence of personal voice or idiosyncrasy.
Do not include any explanation — only the JSON object."""


def classify_with_groq(text: str) -> float:
    """Send text to Groq and return an AI likelihood score in [0.0, 1.0]."""
    client = _get_client()

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.0,
        max_tokens=32,
    )

    raw = response.choices[0].message.content.strip()

    # Extract the numeric score from the JSON response
    match = re.search(r'"score"\s*:\s*([0-9]*\.?[0-9]+)', raw)
    if not match:
        raise ValueError(f"Groq classifier returned unexpected output: {raw!r}")

    score = float(match.group(1))
    return max(0.0, min(1.0, score))
